"""initial operational schema

Revision ID: 23f1110c64a9
Revises:
Create Date: 2026-08-20 16:34:07.837577

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from adsmod_core.repositories.schemas import types as schema_types


revision: str = "23f1110c64a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

###############################################################################
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adsorbates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("inchi_key", sa.String(length=27), nullable=True),
        sa.Column("inchi", sa.String(), nullable=True),
        sa.Column("formula", sa.String(length=255), nullable=True),
        sa.Column("molar_mass_g_mol", sa.Float(), nullable=True),
        sa.Column("smiles", sa.String(), nullable=True),
        sa.Column(
            "created_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inchi_key"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("adsorbates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_adsorbates_normalized_name", ["normalized_name"], unique=False
        )

    op.create_table(
        "adsorbents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("external_identifier", sa.String(length=255), nullable=True),
        sa.Column("formula", sa.String(length=255), nullable=True),
        sa.Column("molar_mass_g_mol", sa.Float(), nullable=True),
        sa.Column("smiles", sa.String(), nullable=True),
        sa.Column(
            "created_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_identifier"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("adsorbents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_adsorbents_normalized_name", ["normalized_name"], unique=False
        )

    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("tags", schema_types.JSONList(), nullable=False),
        sa.Column("provenance", schema_types.JSONMapping(), nullable=False),
        sa.Column(
            "created_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint("source IN ('uploaded', 'nist')", name="ck_datasets_source"),
        sa.CheckConstraint("length(normalized_name) > 0", name="ck_datasets_name"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name", name="uq_datasets_normalized_name"),
    )
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_datasets_source_created_at", ["source", "created_at"], unique=False
        )

    op.create_table(
        "training_datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("configuration", schema_types.JSONMapping(), nullable=False),
        sa.Column("sample_fraction", sa.Float(), nullable=False),
        sa.Column("validation_fraction", sa.Float(), nullable=False),
        sa.Column("min_measurements", sa.Integer(), nullable=True),
        sa.Column("max_measurements", sa.Integer(), nullable=True),
        sa.Column("total_samples", sa.Integer(), nullable=False),
        sa.Column("train_samples", sa.Integer(), nullable=False),
        sa.Column("validation_samples", sa.Integer(), nullable=False),
        sa.Column("test_samples", sa.Integer(), nullable=False),
        sa.Column("vocabularies", schema_types.JSONMapping(), nullable=False),
        sa.Column("normalization_stats", schema_types.JSONMapping(), nullable=False),
        sa.Column(
            "created_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint(
            "min_measurements IS NULL OR max_measurements IS NULL OR min_measurements <= max_measurements",
            name="ck_training_measurement_bounds",
        ),
        sa.CheckConstraint(
            "sample_fraction >= 0 AND sample_fraction <= 1",
            name="ck_training_sample_fraction",
        ),
        sa.CheckConstraint(
            "validation_fraction >= 0 AND validation_fraction <= 1",
            name="ck_training_validation_fraction",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "dataset_imports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("mapping_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_structure", sa.String(length=16), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("column_mapping", schema_types.JSONMapping(), nullable=False),
        sa.Column("validation_result", schema_types.JSONMapping(), nullable=False),
        sa.Column("warnings", schema_types.JSONList(), nullable=False),
        sa.Column(
            "created_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint(
            "source_structure IN ('atomic', 'aggregated', 'mixed')",
            name="ck_dataset_import_structure",
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dataset_id", "source_sha256", name="uq_dataset_import_source"
        ),
    )
    op.create_table(
        "isotherms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("external_key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("adsorbent_id", sa.Integer(), nullable=False),
        sa.Column("temperature_original", sa.Float(), nullable=False),
        sa.Column("temperature_original_unit", sa.String(length=16), nullable=False),
        sa.Column("temperature_k", sa.Float(), nullable=False),
        sa.Column("pressure_basis", sa.String(length=16), nullable=False),
        sa.Column("duplicate_policy", sa.String(length=16), nullable=False),
        sa.Column("saturation_pressure_pa", sa.Float(), nullable=True),
        sa.Column("conditions", schema_types.JSONMapping(), nullable=False),
        sa.Column("provenance", schema_types.JSONMapping(), nullable=False),
        sa.Column(
            "created_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint(
            "duplicate_policy IN ('reject', 'keep', 'average')",
            name="ck_isotherms_duplicate_policy",
        ),
        sa.CheckConstraint(
            "pressure_basis IN ('absolute', 'partial', 'relative')",
            name="ck_isotherms_pressure_basis",
        ),
        sa.CheckConstraint(
            "saturation_pressure_pa IS NULL OR saturation_pressure_pa > 0",
            name="ck_isotherms_saturation_pressure",
        ),
        sa.CheckConstraint("temperature_k > 0", name="ck_isotherms_temperature"),
        sa.ForeignKeyConstraint(
            ["adsorbent_id"], ["adsorbents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dataset_id", "external_key", name="uq_isotherms_dataset_key"
        ),
    )
    with op.batch_alter_table("isotherms", schema=None) as batch_op:
        batch_op.create_index(
            "ix_isotherms_dataset_name", ["dataset_id", "name"], unique=False
        )

    op.create_table(
        "isotherm_components",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("isotherm_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("adsorbate_id", sa.Integer(), nullable=False),
        sa.Column("mole_fraction", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "mole_fraction IS NULL OR (mole_fraction >= 0 AND mole_fraction <= 1)",
            name="ck_components_fraction",
        ),
        sa.CheckConstraint("position >= 1", name="ck_components_position"),
        sa.ForeignKeyConstraint(
            ["adsorbate_id"], ["adsorbates.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["isotherm_id"], ["isotherms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "isotherm_id", "adsorbate_id", name="uq_components_adsorbate"
        ),
        sa.UniqueConstraint("isotherm_id", "position", name="uq_components_position"),
    )
    op.create_table(
        "training_samples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_dataset_id", sa.Integer(), nullable=False),
        sa.Column("sample_key", sa.String(length=255), nullable=False),
        sa.Column("source_isotherm_id", sa.Integer(), nullable=True),
        sa.Column("split", sa.String(length=16), nullable=False),
        sa.Column("temperature_k", sa.Float(), nullable=False),
        sa.Column("pressure_values", schema_types.JSONList(), nullable=False),
        sa.Column("uptake_values", schema_types.JSONList(), nullable=False),
        sa.Column("encoded_adsorbent", sa.Integer(), nullable=True),
        sa.Column("adsorbate_molar_mass", sa.Float(), nullable=True),
        sa.Column("encoded_smiles", schema_types.JSONList(), nullable=True),
        sa.CheckConstraint(
            "split IN ('train', 'validation', 'test')", name="ck_training_samples_split"
        ),
        sa.ForeignKeyConstraint(
            ["source_isotherm_id"], ["isotherms.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["training_dataset_id"], ["training_datasets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "training_dataset_id", "sample_key", name="uq_training_samples_key"
        ),
    )
    with op.batch_alter_table("training_samples", schema=None) as batch_op:
        batch_op.create_index(
            "ix_training_samples_dataset_split",
            ["training_dataset_id", "split"],
            unique=False,
        )

    op.create_table(
        "fitting_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("isotherm_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("optimizer", sa.String(length=32), nullable=False),
        sa.Column("max_evaluations", sa.Integer(), nullable=False),
        sa.Column("pressure_display_unit", sa.String(length=32), nullable=False),
        sa.Column("uptake_display_unit", sa.String(length=32), nullable=False),
        sa.Column("configuration", schema_types.JSONMapping(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("best_result_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", schema_types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "completed_at", schema_types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'warning', 'failed')",
            name="ck_fitting_runs_status",
        ),
        sa.CheckConstraint("max_evaluations > 0", name="ck_fitting_runs_evaluations"),
        sa.ForeignKeyConstraint(
            ["component_id"], ["isotherm_components.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["isotherm_id"], ["isotherms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fitting_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fitting_runs_isotherm_created",
            ["isotherm_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("isotherm_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("pressure_original", sa.Float(), nullable=False),
        sa.Column("pressure_original_unit", sa.String(length=32), nullable=False),
        sa.Column("pressure_canonical", sa.Float(), nullable=False),
        sa.Column("pressure_canonical_unit", sa.String(length=8), nullable=False),
        sa.Column("uptake_original", sa.Float(), nullable=False),
        sa.Column("uptake_original_unit", sa.String(length=32), nullable=False),
        sa.Column("uptake_mol_kg", sa.Float(), nullable=False),
        sa.Column("uptake_stddev_mol_kg", sa.Float(), nullable=True),
        sa.Column("conversion_metadata", schema_types.JSONMapping(), nullable=False),
        sa.Column("extra_metadata", schema_types.JSONMapping(), nullable=False),
        sa.CheckConstraint(
            "pressure_canonical_unit IN ('Pa', '1')",
            name="ck_observations_pressure_unit",
        ),
        sa.CheckConstraint("pressure_canonical >= 0", name="ck_observations_pressure"),
        sa.CheckConstraint("sequence_index >= 0", name="ck_observations_sequence"),
        sa.CheckConstraint("uptake_mol_kg >= 0", name="ck_observations_uptake"),
        sa.CheckConstraint(
            "uptake_stddev_mol_kg IS NULL OR uptake_stddev_mol_kg > 0",
            name="ck_observations_uncertainty",
        ),
        sa.ForeignKeyConstraint(
            ["component_id"], ["isotherm_components.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["isotherm_id"], ["isotherms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "isotherm_id",
            "component_id",
            "sequence_index",
            name="uq_observations_sequence",
        ),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_observations_isotherm_component_pressure",
            ["isotherm_id", "component_id", "pressure_canonical", "sequence_index"],
            unique=False,
        )

    op.create_table(
        "fit_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("convergence_message", sa.String(), nullable=False),
        sa.Column("function_evaluations", sa.Integer(), nullable=True),
        sa.Column("jacobian_rank", sa.Integer(), nullable=True),
        sa.Column("condition_number", sa.Float(), nullable=True),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("parameter_count", sa.Integer(), nullable=False),
        sa.Column("sse", sa.Float(), nullable=True),
        sa.Column("rmse", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("r_squared", sa.Float(), nullable=True),
        sa.Column("adjusted_r_squared", sa.Float(), nullable=True),
        sa.Column("chi_square", sa.Float(), nullable=True),
        sa.Column("aic", sa.Float(), nullable=True),
        sa.Column("aicc", sa.Float(), nullable=True),
        sa.Column("bic", sa.Float(), nullable=True),
        sa.Column("predicted_observations", schema_types.JSONList(), nullable=False),
        sa.Column("predicted_curve", schema_types.JSONList(), nullable=False),
        sa.Column("warnings", schema_types.JSONList(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('success', 'warning', 'failed')", name="ck_fit_results_status"
        ),
        sa.CheckConstraint(
            "observation_count >= 0", name="ck_fit_results_observations"
        ),
        sa.CheckConstraint("parameter_count > 0", name="ck_fit_results_parameters"),
        sa.ForeignKeyConstraint(["run_id"], ["fitting_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "model_name", name="uq_fit_results_run_model"),
    )
    with op.batch_alter_table("fit_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fit_results_run_rank", ["run_id", "rank"], unique=False
        )

    op.create_table(
        "fit_parameters",
        sa.Column("result_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("value_canonical", sa.Float(), nullable=False),
        sa.Column("standard_error_canonical", sa.Float(), nullable=True),
        sa.Column("ci95_low_canonical", sa.Float(), nullable=True),
        sa.Column("ci95_high_canonical", sa.Float(), nullable=True),
        sa.Column("unit_canonical", sa.String(length=128), nullable=False),
        sa.CheckConstraint("position >= 0", name="ck_fit_parameters_position"),
        sa.ForeignKeyConstraint(["result_id"], ["fit_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("result_id", "name"),
        sa.UniqueConstraint("result_id", "position", name="uq_fit_parameters_position"),
    )
    # ### end Alembic commands ###

###############################################################################
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fit_parameters")
    with op.batch_alter_table("fit_results", schema=None) as batch_op:
        batch_op.drop_index("ix_fit_results_run_rank")

    op.drop_table("fit_results")
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index("ix_observations_isotherm_component_pressure")

    op.drop_table("observations")
    with op.batch_alter_table("fitting_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_fitting_runs_isotherm_created")

    op.drop_table("fitting_runs")
    with op.batch_alter_table("training_samples", schema=None) as batch_op:
        batch_op.drop_index("ix_training_samples_dataset_split")

    op.drop_table("training_samples")
    op.drop_table("isotherm_components")
    with op.batch_alter_table("isotherms", schema=None) as batch_op:
        batch_op.drop_index("ix_isotherms_dataset_name")

    op.drop_table("isotherms")
    op.drop_table("dataset_imports")
    op.drop_table("training_datasets")
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.drop_index("ix_datasets_source_created_at")

    op.drop_table("datasets")
    with op.batch_alter_table("adsorbents", schema=None) as batch_op:
        batch_op.drop_index("ix_adsorbents_normalized_name")

    op.drop_table("adsorbents")
    with op.batch_alter_table("adsorbates", schema=None) as batch_op:
        batch_op.drop_index("ix_adsorbates_normalized_name")

    op.drop_table("adsorbates")
    # ### end Alembic commands ###
